name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker test image
      run: docker build -t complex/react-test -f ./client/Dockerfile.dev .
    - name: Execure test cases on test image
      run: docker run -e CI=true complex/react-test npm test -- --coverage
